// flow-typed signature: fa835232953f091c058cfbe308b078b6
// flow-typed version: <<STUB>>/mithril_v^1.1.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mithril'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mithril' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mithril/api/mount' {
  declare module.exports: any;
}

declare module 'mithril/api/redraw' {
  declare module.exports: any;
}

declare module 'mithril/api/router' {
  declare module.exports: any;
}

declare module 'mithril/api/tests/test-mount' {
  declare module.exports: any;
}

declare module 'mithril/api/tests/test-redraw' {
  declare module.exports: any;
}

declare module 'mithril/api/tests/test-router' {
  declare module.exports: any;
}

declare module 'mithril/browser' {
  declare module.exports: any;
}

declare module 'mithril/bundler/bundle' {
  declare module.exports: any;
}

declare module 'mithril/bundler/cli' {
  declare module.exports: any;
}

declare module 'mithril/bundler/minify' {
  declare module.exports: any;
}

declare module 'mithril/bundler/tests/test-bundler' {
  declare module.exports: any;
}

declare module 'mithril/docs/generate' {
  declare module.exports: any;
}

declare module 'mithril/docs/lint' {
  declare module.exports: any;
}

declare module 'mithril/examples/dbmonster/angular/app' {
  declare module.exports: any;
}

declare module 'mithril/examples/dbmonster/ENV' {
  declare module.exports: any;
}

declare module 'mithril/examples/dbmonster/memory-stats' {
  declare module.exports: any;
}

declare module 'mithril/examples/dbmonster/mithril/app' {
  declare module.exports: any;
}

declare module 'mithril/examples/dbmonster/monitor' {
  declare module.exports: any;
}

declare module 'mithril/examples/dbmonster/react/app' {
  declare module.exports: any;
}

declare module 'mithril/examples/dbmonster/vue/app' {
  declare module.exports: any;
}

declare module 'mithril/examples/threaditjs/app' {
  declare module.exports: any;
}

declare module 'mithril/examples/todomvc/todomvc' {
  declare module.exports: any;
}

declare module 'mithril/hyperscript' {
  declare module.exports: any;
}

declare module 'mithril/mithril' {
  declare module.exports: any;
}

declare module 'mithril/mithril.min' {
  declare module.exports: any;
}

declare module 'mithril/module/module' {
  declare module.exports: any;
}

declare module 'mithril/mount' {
  declare module.exports: any;
}

declare module 'mithril/ospec/ospec' {
  declare module.exports: any;
}

declare module 'mithril/ospec/tests/test-ospec' {
  declare module.exports: any;
}

declare module 'mithril/promise/promise' {
  declare module.exports: any;
}

declare module 'mithril/promise/tests/test-promise' {
  declare module.exports: any;
}

declare module 'mithril/querystring/build' {
  declare module.exports: any;
}

declare module 'mithril/querystring/parse' {
  declare module.exports: any;
}

declare module 'mithril/querystring/tests/test-buildQueryString' {
  declare module.exports: any;
}

declare module 'mithril/querystring/tests/test-parseQueryString' {
  declare module.exports: any;
}

declare module 'mithril/redraw' {
  declare module.exports: any;
}

declare module 'mithril/render' {
  declare module.exports: any;
}

declare module 'mithril/render/fragment' {
  declare module.exports: any;
}

declare module 'mithril/render/hyperscript' {
  declare module.exports: any;
}

declare module 'mithril/render/render' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-attributes' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-component' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-createElement' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-createFragment' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-createHTML' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-createNodes' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-createText' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-event' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-fragment' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-hyperscript' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-input' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-normalize' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-normalizeChildren' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-onbeforeremove' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-onbeforeupdate' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-oncreate' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-oninit' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-onremove' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-onupdate' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-render' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-textContent' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-trust' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-updateElement' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-updateFragment' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-updateHTML' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-updateNodes' {
  declare module.exports: any;
}

declare module 'mithril/render/tests/test-updateText' {
  declare module.exports: any;
}

declare module 'mithril/render/trust' {
  declare module.exports: any;
}

declare module 'mithril/render/vnode' {
  declare module.exports: any;
}

declare module 'mithril/request' {
  declare module.exports: any;
}

declare module 'mithril/request/request' {
  declare module.exports: any;
}

declare module 'mithril/request/tests/test-jsonp' {
  declare module.exports: any;
}

declare module 'mithril/request/tests/test-request' {
  declare module.exports: any;
}

declare module 'mithril/route' {
  declare module.exports: any;
}

declare module 'mithril/router/router' {
  declare module.exports: any;
}

declare module 'mithril/router/tests/test-defineRoutes' {
  declare module.exports: any;
}

declare module 'mithril/router/tests/test-getPath' {
  declare module.exports: any;
}

declare module 'mithril/router/tests/test-setPath' {
  declare module.exports: any;
}

declare module 'mithril/stream' {
  declare module.exports: any;
}

declare module 'mithril/stream/stream' {
  declare module.exports: any;
}

declare module 'mithril/stream/tests/test-scan' {
  declare module.exports: any;
}

declare module 'mithril/stream/tests/test-scanMerge' {
  declare module.exports: any;
}

declare module 'mithril/stream/tests/test-stream' {
  declare module.exports: any;
}

declare module 'mithril/test-utils/browserMock' {
  declare module.exports: any;
}

declare module 'mithril/test-utils/callAsync' {
  declare module.exports: any;
}

declare module 'mithril/test-utils/components' {
  declare module.exports: any;
}

declare module 'mithril/test-utils/domMock' {
  declare module.exports: any;
}

declare module 'mithril/test-utils/parseURL' {
  declare module.exports: any;
}

declare module 'mithril/test-utils/pushStateMock' {
  declare module.exports: any;
}

declare module 'mithril/test-utils/tests/test-browserMock' {
  declare module.exports: any;
}

declare module 'mithril/test-utils/tests/test-callAsync' {
  declare module.exports: any;
}

declare module 'mithril/test-utils/tests/test-components' {
  declare module.exports: any;
}

declare module 'mithril/test-utils/tests/test-domMock' {
  declare module.exports: any;
}

declare module 'mithril/test-utils/tests/test-parseURL' {
  declare module.exports: any;
}

declare module 'mithril/test-utils/tests/test-pushStateMock' {
  declare module.exports: any;
}

declare module 'mithril/test-utils/tests/test-xhrMock' {
  declare module.exports: any;
}

declare module 'mithril/test-utils/xhrMock' {
  declare module.exports: any;
}

declare module 'mithril/tests/test-api' {
  declare module.exports: any;
}

declare module 'mithril/util/tests/test-withAttr' {
  declare module.exports: any;
}

declare module 'mithril/util/withAttr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mithril/api/mount.js' {
  declare module.exports: $Exports<'mithril/api/mount'>;
}
declare module 'mithril/api/redraw.js' {
  declare module.exports: $Exports<'mithril/api/redraw'>;
}
declare module 'mithril/api/router.js' {
  declare module.exports: $Exports<'mithril/api/router'>;
}
declare module 'mithril/api/tests/test-mount.js' {
  declare module.exports: $Exports<'mithril/api/tests/test-mount'>;
}
declare module 'mithril/api/tests/test-redraw.js' {
  declare module.exports: $Exports<'mithril/api/tests/test-redraw'>;
}
declare module 'mithril/api/tests/test-router.js' {
  declare module.exports: $Exports<'mithril/api/tests/test-router'>;
}
declare module 'mithril/browser.js' {
  declare module.exports: $Exports<'mithril/browser'>;
}
declare module 'mithril/bundler/bundle.js' {
  declare module.exports: $Exports<'mithril/bundler/bundle'>;
}
declare module 'mithril/bundler/cli.js' {
  declare module.exports: $Exports<'mithril/bundler/cli'>;
}
declare module 'mithril/bundler/minify.js' {
  declare module.exports: $Exports<'mithril/bundler/minify'>;
}
declare module 'mithril/bundler/tests/test-bundler.js' {
  declare module.exports: $Exports<'mithril/bundler/tests/test-bundler'>;
}
declare module 'mithril/docs/generate.js' {
  declare module.exports: $Exports<'mithril/docs/generate'>;
}
declare module 'mithril/docs/lint.js' {
  declare module.exports: $Exports<'mithril/docs/lint'>;
}
declare module 'mithril/examples/dbmonster/angular/app.js' {
  declare module.exports: $Exports<'mithril/examples/dbmonster/angular/app'>;
}
declare module 'mithril/examples/dbmonster/ENV.js' {
  declare module.exports: $Exports<'mithril/examples/dbmonster/ENV'>;
}
declare module 'mithril/examples/dbmonster/memory-stats.js' {
  declare module.exports: $Exports<'mithril/examples/dbmonster/memory-stats'>;
}
declare module 'mithril/examples/dbmonster/mithril/app.js' {
  declare module.exports: $Exports<'mithril/examples/dbmonster/mithril/app'>;
}
declare module 'mithril/examples/dbmonster/monitor.js' {
  declare module.exports: $Exports<'mithril/examples/dbmonster/monitor'>;
}
declare module 'mithril/examples/dbmonster/react/app.js' {
  declare module.exports: $Exports<'mithril/examples/dbmonster/react/app'>;
}
declare module 'mithril/examples/dbmonster/vue/app.js' {
  declare module.exports: $Exports<'mithril/examples/dbmonster/vue/app'>;
}
declare module 'mithril/examples/threaditjs/app.js' {
  declare module.exports: $Exports<'mithril/examples/threaditjs/app'>;
}
declare module 'mithril/examples/todomvc/todomvc.js' {
  declare module.exports: $Exports<'mithril/examples/todomvc/todomvc'>;
}
declare module 'mithril/hyperscript.js' {
  declare module.exports: $Exports<'mithril/hyperscript'>;
}
declare module 'mithril/index' {
  declare module.exports: $Exports<'mithril'>;
}
declare module 'mithril/index.js' {
  declare module.exports: $Exports<'mithril'>;
}
declare module 'mithril/mithril.js' {
  declare module.exports: $Exports<'mithril/mithril'>;
}
declare module 'mithril/mithril.min.js' {
  declare module.exports: $Exports<'mithril/mithril.min'>;
}
declare module 'mithril/module/module.js' {
  declare module.exports: $Exports<'mithril/module/module'>;
}
declare module 'mithril/mount.js' {
  declare module.exports: $Exports<'mithril/mount'>;
}
declare module 'mithril/ospec/ospec.js' {
  declare module.exports: $Exports<'mithril/ospec/ospec'>;
}
declare module 'mithril/ospec/tests/test-ospec.js' {
  declare module.exports: $Exports<'mithril/ospec/tests/test-ospec'>;
}
declare module 'mithril/promise/promise.js' {
  declare module.exports: $Exports<'mithril/promise/promise'>;
}
declare module 'mithril/promise/tests/test-promise.js' {
  declare module.exports: $Exports<'mithril/promise/tests/test-promise'>;
}
declare module 'mithril/querystring/build.js' {
  declare module.exports: $Exports<'mithril/querystring/build'>;
}
declare module 'mithril/querystring/parse.js' {
  declare module.exports: $Exports<'mithril/querystring/parse'>;
}
declare module 'mithril/querystring/tests/test-buildQueryString.js' {
  declare module.exports: $Exports<'mithril/querystring/tests/test-buildQueryString'>;
}
declare module 'mithril/querystring/tests/test-parseQueryString.js' {
  declare module.exports: $Exports<'mithril/querystring/tests/test-parseQueryString'>;
}
declare module 'mithril/redraw.js' {
  declare module.exports: $Exports<'mithril/redraw'>;
}
declare module 'mithril/render.js' {
  declare module.exports: $Exports<'mithril/render'>;
}
declare module 'mithril/render/fragment.js' {
  declare module.exports: $Exports<'mithril/render/fragment'>;
}
declare module 'mithril/render/hyperscript.js' {
  declare module.exports: $Exports<'mithril/render/hyperscript'>;
}
declare module 'mithril/render/render.js' {
  declare module.exports: $Exports<'mithril/render/render'>;
}
declare module 'mithril/render/tests/test-attributes.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-attributes'>;
}
declare module 'mithril/render/tests/test-component.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-component'>;
}
declare module 'mithril/render/tests/test-createElement.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-createElement'>;
}
declare module 'mithril/render/tests/test-createFragment.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-createFragment'>;
}
declare module 'mithril/render/tests/test-createHTML.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-createHTML'>;
}
declare module 'mithril/render/tests/test-createNodes.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-createNodes'>;
}
declare module 'mithril/render/tests/test-createText.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-createText'>;
}
declare module 'mithril/render/tests/test-event.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-event'>;
}
declare module 'mithril/render/tests/test-fragment.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-fragment'>;
}
declare module 'mithril/render/tests/test-hyperscript.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-hyperscript'>;
}
declare module 'mithril/render/tests/test-input.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-input'>;
}
declare module 'mithril/render/tests/test-normalize.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-normalize'>;
}
declare module 'mithril/render/tests/test-normalizeChildren.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-normalizeChildren'>;
}
declare module 'mithril/render/tests/test-onbeforeremove.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-onbeforeremove'>;
}
declare module 'mithril/render/tests/test-onbeforeupdate.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-onbeforeupdate'>;
}
declare module 'mithril/render/tests/test-oncreate.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-oncreate'>;
}
declare module 'mithril/render/tests/test-oninit.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-oninit'>;
}
declare module 'mithril/render/tests/test-onremove.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-onremove'>;
}
declare module 'mithril/render/tests/test-onupdate.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-onupdate'>;
}
declare module 'mithril/render/tests/test-render.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-render'>;
}
declare module 'mithril/render/tests/test-textContent.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-textContent'>;
}
declare module 'mithril/render/tests/test-trust.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-trust'>;
}
declare module 'mithril/render/tests/test-updateElement.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-updateElement'>;
}
declare module 'mithril/render/tests/test-updateFragment.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-updateFragment'>;
}
declare module 'mithril/render/tests/test-updateHTML.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-updateHTML'>;
}
declare module 'mithril/render/tests/test-updateNodes.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-updateNodes'>;
}
declare module 'mithril/render/tests/test-updateText.js' {
  declare module.exports: $Exports<'mithril/render/tests/test-updateText'>;
}
declare module 'mithril/render/trust.js' {
  declare module.exports: $Exports<'mithril/render/trust'>;
}
declare module 'mithril/render/vnode.js' {
  declare module.exports: $Exports<'mithril/render/vnode'>;
}
declare module 'mithril/request.js' {
  declare module.exports: $Exports<'mithril/request'>;
}
declare module 'mithril/request/request.js' {
  declare module.exports: $Exports<'mithril/request/request'>;
}
declare module 'mithril/request/tests/test-jsonp.js' {
  declare module.exports: $Exports<'mithril/request/tests/test-jsonp'>;
}
declare module 'mithril/request/tests/test-request.js' {
  declare module.exports: $Exports<'mithril/request/tests/test-request'>;
}
declare module 'mithril/route.js' {
  declare module.exports: $Exports<'mithril/route'>;
}
declare module 'mithril/router/router.js' {
  declare module.exports: $Exports<'mithril/router/router'>;
}
declare module 'mithril/router/tests/test-defineRoutes.js' {
  declare module.exports: $Exports<'mithril/router/tests/test-defineRoutes'>;
}
declare module 'mithril/router/tests/test-getPath.js' {
  declare module.exports: $Exports<'mithril/router/tests/test-getPath'>;
}
declare module 'mithril/router/tests/test-setPath.js' {
  declare module.exports: $Exports<'mithril/router/tests/test-setPath'>;
}
declare module 'mithril/stream.js' {
  declare module.exports: $Exports<'mithril/stream'>;
}
declare module 'mithril/stream/stream.js' {
  declare module.exports: $Exports<'mithril/stream/stream'>;
}
declare module 'mithril/stream/tests/test-scan.js' {
  declare module.exports: $Exports<'mithril/stream/tests/test-scan'>;
}
declare module 'mithril/stream/tests/test-scanMerge.js' {
  declare module.exports: $Exports<'mithril/stream/tests/test-scanMerge'>;
}
declare module 'mithril/stream/tests/test-stream.js' {
  declare module.exports: $Exports<'mithril/stream/tests/test-stream'>;
}
declare module 'mithril/test-utils/browserMock.js' {
  declare module.exports: $Exports<'mithril/test-utils/browserMock'>;
}
declare module 'mithril/test-utils/callAsync.js' {
  declare module.exports: $Exports<'mithril/test-utils/callAsync'>;
}
declare module 'mithril/test-utils/components.js' {
  declare module.exports: $Exports<'mithril/test-utils/components'>;
}
declare module 'mithril/test-utils/domMock.js' {
  declare module.exports: $Exports<'mithril/test-utils/domMock'>;
}
declare module 'mithril/test-utils/parseURL.js' {
  declare module.exports: $Exports<'mithril/test-utils/parseURL'>;
}
declare module 'mithril/test-utils/pushStateMock.js' {
  declare module.exports: $Exports<'mithril/test-utils/pushStateMock'>;
}
declare module 'mithril/test-utils/tests/test-browserMock.js' {
  declare module.exports: $Exports<'mithril/test-utils/tests/test-browserMock'>;
}
declare module 'mithril/test-utils/tests/test-callAsync.js' {
  declare module.exports: $Exports<'mithril/test-utils/tests/test-callAsync'>;
}
declare module 'mithril/test-utils/tests/test-components.js' {
  declare module.exports: $Exports<'mithril/test-utils/tests/test-components'>;
}
declare module 'mithril/test-utils/tests/test-domMock.js' {
  declare module.exports: $Exports<'mithril/test-utils/tests/test-domMock'>;
}
declare module 'mithril/test-utils/tests/test-parseURL.js' {
  declare module.exports: $Exports<'mithril/test-utils/tests/test-parseURL'>;
}
declare module 'mithril/test-utils/tests/test-pushStateMock.js' {
  declare module.exports: $Exports<'mithril/test-utils/tests/test-pushStateMock'>;
}
declare module 'mithril/test-utils/tests/test-xhrMock.js' {
  declare module.exports: $Exports<'mithril/test-utils/tests/test-xhrMock'>;
}
declare module 'mithril/test-utils/xhrMock.js' {
  declare module.exports: $Exports<'mithril/test-utils/xhrMock'>;
}
declare module 'mithril/tests/test-api.js' {
  declare module.exports: $Exports<'mithril/tests/test-api'>;
}
declare module 'mithril/util/tests/test-withAttr.js' {
  declare module.exports: $Exports<'mithril/util/tests/test-withAttr'>;
}
declare module 'mithril/util/withAttr.js' {
  declare module.exports: $Exports<'mithril/util/withAttr'>;
}
